# Generated by Django 4.2.7 on 2023-11-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='abcccc', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
